### ISSUE TITLE
could not find function "jSDM_binomial_probit_block"

### ISSUE THREAD

**Issue by arteteco** [ghislainv/jSDM#12]
hello everyone,
just installed jSDM using the CRAN repo, as `install.packages("jSDM")`. All good.

I'm running though the [frog example](https://ecology.ghislainv.fr/jSDM/articles/jSDM.html), using my own dataset, but when I get to the `jSDM_binomial_probit_block` function I have the following error

```
Error in jSDM_binomial_probit_block(burnin = 1000, mcmc = 1000, thin = 1,  : 
  could not find function "jSDM_binomial_probit_block"
```

This is the code I'm using 

```
probit <- jSDM_binomial_probit_block(
  # Chains
  burnin=1000, mcmc=1000, thin=1,
  # Response variable 
  presence_site_sp = data, 
  # Explanatory variables 
  site_suitability = ~.,   
  site_data = envars,
  # Model specification 
  n_latent=2, site_effect="random",
  # Starting values
  alpha_start=0, beta_start=0,
  lambda_start=0, W_start=0,
  V_alpha=1, 
  # Priors
  shape=0.1, rate=0.1,
  mu_beta=0, V_beta=10,
  mu_lambda=0, V_lambda=10,
  # Various 
  seed=1234, verbose=1)
```

Of course, I've imported the library and I can see `?jSDM` just fine.

Any help on why this may happen?

Thanks!

**Comment by JeanneClement** [comment]
Hello, the functions of this package under development have been renamed since the latest CRAN release, the function jSDM_binomial_probit_block is named jSDM_probit_block() in the package available on CRAN. 
Sorry for the confusion, we will soon update the version of jSDM available on CRAN, in the meantime you can install the latest version from Github. 

Best regards
